name: fun_pro_pkg
description: Fun Pro Package.
version: 1.0.0
repository: https://github.com/mcarlosco/fun_pro_pkg

environment:
  sdk: ^3.5.3

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
